### ISSUE TITLE
broken - http://bruth.github.io/jekyll-docs-template

### ISSUE THREAD

**Issue by koxon** [bruth/jekyll-docs-template#24]
The gh-pages documentation URL is broken:
http://bruth.github.io/jekyll-docs-template

**Comment by bruth** [comment]
It is not for me. Can you check again?

**Comment by koxon** [comment]
It's back on. I think GitHub was having issues.

Sorry for the trouble.

Thanks
nico

On Mon, Jul 6, 2015 at 8:32 PM, Byron Ruth <notifications@github.com> wrote:

> It is not for me. Can you check again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bruth/jekyll-docs-template/issues/24#issuecomment-119034906>
> .
>



-- 
Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.
