### ISSUE TITLE
redcarpet is no longer supported by GitHub pages

### ISSUE THREAD

**Issue by az0** [bruth/jekyll-docs-template#28]
Every time I push, GitHub emails me a warning

>The page build completed successfully, but returned the following warning for the `gh-pages` branch:

>You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/.

P.S., thank you for the nice template

**Comment by srbala** [comment]
@az0 markdown engine changed to kramdown, you can close this issue
